### ISSUE TITLE
Apostrophes (') added around leaf labels

### ISSUE THREAD

**Issue by niemasd** [uym2/MP_reroot#8]
In the datasets I was running, apostrophes were added around some leaf labels. For example, `N58960|CNG0-COM16-4230|8.407322` became `'N58960|CNG0-COM16-4230|8.407322'`. I believe this is an artifact from how DendroPy outputs the Newick strings. In my specific datasets, I'm simply removing all apostrophes, but it might be good to fix this internally so that it will work cleanly on trees in which some leaves truly have apostrophes in their names

**Comment by niemasd** [comment]
It might be good to fix this at some point :-)

**Comment by uym2** [comment]
Thank you for pointing this out!
I fixed the issue so that it does not add apostrophes automatically. Can you give it a quick test or send me a small tree with/without apostrophes to test?

**Comment by niemasd** [comment]
Thank you, Uyen! I have attached a tree that used to add apostophes

[example.txt](https://github.com/uym2/MinVar-Rooting/files/4588430/example.txt)

**Comment by uym2** [comment]
I tested and saw no apostophes added. I will close this issue for now. Let me know if you encounter similar problems in the future.

**Comment by niemasd** [comment]
Thank you so much!!
